### ISSUE TITLE
Why not build directly from the rclone version?

### ISSUE THREAD

**Issue by MythodeaLoL** [javi11/usenet-drive#110]
Why not build this integration taking, for example, the most current build of rclone, wouldn't it be beneficial for a possible official adoption by rclone in the future via a pull request?

Would I be able to implement your usenet update in the rclone build without compatibility problems? I would like to use other remotes and functions from my own version of rclone.

I would like to congratulate you on the project, it is very interesting, I liked it. The rclone dev was looking for something like this years ago so he could use it as a base and add support for this officially in rclone. 

It would be great to have the best of both worlds together @javi11 :)

**Comment by javi11** [comment]
Hey @MythodeaLoL,
I thought about that previously and I also think that will be beneficial but, there are some aspects that I think it prevents to be integrated as rclone backend:

- Is not stable yet, that will be a temporary problem.
- In Usenet you can not modify files, not sure if because of that they do not let include this on the official build
- I have plans to include background tasks such, reupload articles once they are about to expire, also a front to manage this and a part of that tasks to repair archives. Anyway this can be included as part of a separates tool 

Anyway I don’t discard to include it in a future and if you want to do it, feel free :)

**Comment by MythodeaLoL** [comment]
You could simply create a function to reupload the modified files, this would be an "edit", the already uploaded file would be lost, since it is not possible to modify it, you would just leave it in oblivion.

**Comment by javi11** [comment]
That will be dangerous because you will fill Usenet with duplicate data making your files to be deleted as they will probably be marked as spam.Also in file edits you don’t have all the file you will need to edit by pices

**Comment by javi11** [comment]
I will close this one for the moment since is not yet on the plans to do it, but I will take it in account for the future ;)
