### ISSUE TITLE
One more noobish query

### ISSUE THREAD

**Issue by j0hnckuy** [javi11/usenet-drive#150]
Is local file storage say /temp accessed when trying to send files over to someone? Or is it that that someone receives the files directly from usenet itlself? What happens in the background when someone would click to download my file from self-hosted p2p client.. like is it that the files would be accessed on usenet and it gets downloaded to local system (somewhere) and then the local system sends the file over to that "someone"? It's all got me confused a bit. What if I host it on a flash drive of 5 GiB and someone tries to download 10 GiB oh hosted file? Will my flash run out of memory?

**Comment by javi11** [comment]
It will works by streaming so if you have you webdav server mounted at the folder c:/my-mount when somebody access to c:/my-mount/myfile.txt the file will be downloaded from Usenet using your account and transmitted to that user without downloading it to your local system. So in your case of a flash of 5gIB you can perfectly download some file of 10 GiB because it won´t be downloaded to that flash card.

Be aware of sharing files using your usenet account and abusing downloading a lot of TB of data share it with a lot of people because you will be most probably get a ban from the usenet provider XD  mostly for the amount of data downloaded.

**Comment by javi11** [comment]
Hey yes, don´t worry for the connections you can set that as the default 15 or 20 the tool will manage the connections between the access, in my tests you can get decent access speeds for at least 10 or 20 downloads with 50 connections :)
